# Generated by Django 5.2.7 on 2025-10-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='carclass',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='contracttype',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='functionallocation',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='notificationrecipient',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='name_ar',
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('operational', 'عاملة'), ('new', 'جديدة'), ('defective', 'معطلة'), ('under_maintenance', 'تحت الصيانة')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('operational', 'عاملة'), ('new', 'جديدة'), ('defective', 'معطلة'), ('under_maintenance', 'تحت الصيانة')], default='new', max_length=50),
        ),
    ]
