# Generated by Django 5.2.7 on 2025-10-17 01:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_remove_activity_name_ar_remove_carclass_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إدارة',
                'verbose_name_plural': 'الإدارات',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'نشاط', 'verbose_name_plural': 'الأنشطة'},
        ),
        migrations.AlterModelOptions(
            name='calibrationcertificateimage',
            options={'verbose_name': 'شهادة معايرة', 'verbose_name_plural': 'شهادات المعايرة'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'سيارة', 'verbose_name_plural': 'السيارات'},
        ),
        migrations.AlterModelOptions(
            name='carclass',
            options={'verbose_name': 'فئة السيارة', 'verbose_name_plural': 'فئات السيارات'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'موديل السيارة', 'verbose_name_plural': 'موديلات السيارات'},
        ),
        migrations.AlterModelOptions(
            name='contracttype',
            options={'verbose_name': 'نوع العقد', 'verbose_name_plural': 'أنواع العقود'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'سائق', 'verbose_name_plural': 'السائقين'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'معدة', 'verbose_name_plural': 'المعدات'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'verbose_name': 'موديل المعدة', 'verbose_name_plural': 'موديلات المعدات'},
        ),
        migrations.AlterModelOptions(
            name='functionallocation',
            options={'verbose_name': 'الموقع الوظيفي', 'verbose_name_plural': 'المواقع الوظيفية'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'موقع', 'verbose_name_plural': 'المواقع'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-maintenance_date'], 'verbose_name': 'صيانة', 'verbose_name_plural': 'سجلات الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'الشركة المصنعة', 'verbose_name_plural': 'الشركات المصنعة'},
        ),
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'verbose_name': 'مستلم الإشعار', 'verbose_name_plural': 'مستلمي الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'منطقة', 'verbose_name_plural': 'المناطق'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'غرفة', 'verbose_name_plural': 'الغرف'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'قطاع', 'verbose_name_plural': 'القطاعات'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='calibrationcertificateimage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_certificates', to='inventory.equipment', verbose_name='المعدة'),
        ),
        migrations.AlterField(
            model_name='calibrationcertificateimage',
            name='image',
            field=models.ImageField(upload_to='calibration_certificates/', verbose_name='شهادة المعايرة'),
        ),
        migrations.AlterField(
            model_name='calibrationcertificateimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='car',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.activity', verbose_name='النشاط'),
        ),
        migrations.AlterField(
            model_name='car',
            name='address_details_1',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل العنوان 1'),
        ),
        migrations.AlterField(
            model_name='car',
            name='annual_inspection_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الفحص السنوي'),
        ),
        migrations.AlterField(
            model_name='car',
            name='annual_inspection_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الفحص السنوي'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.carclass', verbose_name='فئة السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_license_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء رخصة السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_license_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية رخصة السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.contracttype', verbose_name='نوع العقد'),
        ),
        migrations.AlterField(
            model_name='car',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.department', verbose_name='رمز القسم'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.driver', verbose_name='اسم السائق'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fleet_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='رقم الأسطول'),
        ),
        migrations.AlterField(
            model_name='car',
            name='functional_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.functionallocation', verbose_name='الموقع الوظيفي'),
        ),
        migrations.AlterField(
            model_name='car',
            name='location_description',
            field=models.TextField(verbose_name='وصف الموقع'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.carmodel', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='car',
            name='notification_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.notificationrecipient', verbose_name='مستلم الإشعار'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('leased_regular', 'Leased - Regular'), ('leased_non_regular', 'Leased - Non Regular'), ('leased_emp_24hrs', 'Leased - Emp 24hrs')], default='owned', max_length=50, verbose_name='نوع الملكية'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_no_ar',
            field=models.CharField(max_length=100, unique=True, verbose_name='رقم اللوحة (العربية)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_no_en',
            field=models.CharField(max_length=100, unique=True, verbose_name='رقم اللوحة (الإنجليزية)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.room', verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('operational', 'عاملة'), ('new', 'جديدة'), ('defective', 'معطلة'), ('under_maintenance', 'تحت الصيانة')], default='new', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='visited_regions',
            field=models.ManyToManyField(blank=True, related_name='cars', to='inventory.region', verbose_name='المناطق المزارة'),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='carclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الرخصة'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='annual_inspection_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الفحص السنوي'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='annual_inspection_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الفحص السنوي'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='door_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='رقم الباب'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='صورة المعدة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_license_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء رخصة المعدة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_license_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية رخصة المعدة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.location', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)], verbose_name='سنة التصنيع'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.equipmentmodel', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='plate_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='رقم اللوحة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.sector', verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('operational', 'عاملة'), ('new', 'جديدة'), ('defective', 'معطلة'), ('under_maintenance', 'تحت الصيانة')], default='new', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_models', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='functionallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='functionallocation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='functionallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع المحتوى'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصيانة'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='معرف الكائن'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='restoration_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإصلاح'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الطابق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='car',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.administrativeunit', verbose_name='الإدارة'),
        ),
    ]
