# Generated by Django 5.2.7 on 2025-10-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_administrativeunit_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.administrativeunit', verbose_name='الإدارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.carclass', verbose_name='فئة السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='department_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.department', verbose_name='رمز القسم'),
        ),
        migrations.AlterField(
            model_name='car',
            name='functional_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.functionallocation', verbose_name='الموقع الوظيفي'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.carmodel', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.location', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.equipmentmodel', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='inventory.sector', verbose_name='القطاع'),
        ),
    ]
