# Generated by Django 5.2.7 on 2025-10-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_protected_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.activity', verbose_name='النشاط'),
        ),
        migrations.AlterField(
            model_name='car',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.administrativeunit', verbose_name='الإدارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.carclass', verbose_name='فئة السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.contracttype', verbose_name='نوع العقد'),
        ),
        migrations.AlterField(
            model_name='car',
            name='department_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.department', verbose_name='رمز القسم'),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.driver', verbose_name='اسم السائق'),
        ),
        migrations.AlterField(
            model_name='car',
            name='functional_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.functionallocation', verbose_name='الموقع الوظيفي'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.carmodel', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='car',
            name='notification_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.notificationrecipient', verbose_name='مستلم الإشعار'),
        ),
        migrations.AlterField(
            model_name='car',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.room', verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_models', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.location', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.equipmentmodel', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.sector', verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='inventory.manufacturer', verbose_name='الشركة المصنعة'),
        ),
    ]
