# Generated by Django 5.2.7 on 2025-10-24 01:08

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_images(apps, schema_editor):
    """Migrate existing single images to the new multiple image models"""
    Car = apps.get_model('inventory', 'Car')
    Equipment = apps.get_model('inventory', 'Equipment')
    CarImage = apps.get_model('inventory', 'CarImage')
    EquipmentImage = apps.get_model('inventory', 'EquipmentImage')
    
    # Migrate car images
    for car in Car.objects.filter(car_image__isnull=False).exclude(car_image=''):
        CarImage.objects.create(
            car=car,
            image=car.car_image
        )
    
    # Migrate equipment images
    for equipment in Equipment.objects.filter(equipment_image__isnull=False).exclude(equipment_image=''):
        EquipmentImage.objects.create(
            equipment=equipment,
            image=equipment.equipment_image
        )


def reverse_migrate_images(apps, schema_editor):
    """Reverse migration - this is not implemented as we don't want to lose data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_revert_to_protected_delete_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='صورة السيارة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='inventory.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'صورة سيارة',
                'verbose_name_plural': 'صور السيارات',
            },
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='صورة المعدة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_images', to='inventory.equipment', verbose_name='المعدة')),
            ],
            options={
                'verbose_name': 'صورة معدة',
                'verbose_name_plural': 'صور المعدات',
            },
        ),
        migrations.RunPython(migrate_existing_images, reverse_migrate_images),
    ]
