# Generated by Django 5.2.7 on 2025-10-24 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_multiple_image_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='annual_inspection_end_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='annual_inspection_start_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_license_end_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_license_start_date',
        ),
        migrations.CreateModel(
            name='CarInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الفحص')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الفحص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='inventory.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'سجل فحص سيارة',
                'verbose_name_plural': 'سجلات فحص السيارات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CarLicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الرخصة')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الرخصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_records', to='inventory.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'سجل رخصة سيارة',
                'verbose_name_plural': 'سجلات رخص السيارات',
                'ordering': ['-start_date'],
            },
        ),
    ]
