# Generated by Django 5.2.7 on 2025-10-24 01:48

from django.db import migrations


def migrate_existing_data(apps, schema_editor):
    """Migrate existing license and inspection data to new historical records"""
    # This migration is no longer needed as the fields were already removed
    # The data migration should have been run before removing the fields
    pass


def reverse_migrate_data(apps, schema_editor):
    """Reverse migration - this is not possible as we're removing fields"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_historical_license_inspection_records'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_data, reverse_migrate_data),
    ]
