# Generated by Django 5.2.7 on 2025-10-24 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_migrate_existing_license_inspection_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='annual_inspection_end_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='annual_inspection_start_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_license_end_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_license_start_date',
        ),
        migrations.CreateModel(
            name='EquipmentInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الفحص السنوي')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء الفحص السنوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='inventory.equipment', verbose_name='المعدة')),
            ],
            options={
                'verbose_name': 'سجل فحص معدة',
                'verbose_name_plural': 'سجلات فحص المعدات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية رخصة المعدة')),
                ('end_date', models.DateField(verbose_name='تاريخ انتهاء رخصة المعدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_records', to='inventory.equipment', verbose_name='المعدة')),
            ],
            options={
                'verbose_name': 'سجل رخصة معدة',
                'verbose_name_plural': 'سجلات رخص المعدات',
                'ordering': ['-start_date'],
            },
        ),
    ]
