# Generated by Django 5.2.7 on 2025-10-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_equipment_annual_inspection_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationcertificateimage',
            name='image',
            field=models.FileField(upload_to='calibration_certificates/', verbose_name='شهادة المعايرة'),
        ),
    ]
