# Generated by Django 5.2.7 on 2025-10-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_change_calibration_certificate_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireExtinguisherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fire_extinguishers/', verbose_name='صورة طفاية الحريق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_extinguisher_images', to='inventory.equipment', verbose_name='المعدة')),
            ],
            options={
                'verbose_name': 'صورة طفاية حريق',
                'verbose_name_plural': 'صور طفايات الحريق',
            },
        ),
        migrations.CreateModel(
            name='FireExtinguisherInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='تاريخ الفحص الدوري لطفاية الحريق')),
                ('expiry_date', models.DateField(verbose_name='تاريخ انتهاء طفاية الحريق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_extinguisher_records', to='inventory.equipment', verbose_name='المعدة')),
            ],
            options={
                'verbose_name': 'سجل فحص طفاية حريق',
                'verbose_name_plural': 'سجلات فحص طفايات الحريق',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
