# Generated by Django 4.2.7 on 2025-10-31 12:00

from django.db import migrations, models
import django.db.models.deletion


def create_dummy_records(apps, schema_editor):
    """Create dummy Sector, Department, and Division records"""
    Sector = apps.get_model('inventory', 'Sector')
    Department = apps.get_model('inventory', 'Department')
    Division = apps.get_model('inventory', 'Division')
    
    # Create dummy Sector
    dummy_sector, created = Sector.objects.get_or_create(
        name='غير محدد',
        defaults={'is_dummy': True}
    )
    
    # Create dummy Department linked to dummy Sector
    dummy_department, created = Department.objects.get_or_create(
        name='غير محدد',
        defaults={'sector': dummy_sector, 'is_dummy': True}
    )
    
    # Create dummy Division linked to dummy Department
    Division.objects.get_or_create(
        name='غير محدد',
        defaults={'department': dummy_department, 'is_dummy': True}
    )


def reverse_dummy_records(apps, schema_editor):
    """Remove dummy records"""
    Sector = apps.get_model('inventory', 'Sector')
    Department = apps.get_model('inventory', 'Department')
    Division = apps.get_model('inventory', 'Division')
    
    Division.objects.filter(name='غير محدد', is_dummy=True).delete()
    Department.objects.filter(name='غير محدد', is_dummy=True).delete()
    Sector.objects.filter(name='غير محدد', is_dummy=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_setup_rbac_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_by_department', to='inventory.department', verbose_name='الإدارة'),
        ),
        migrations.AddField(
            model_name='car',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_by_sector', to='inventory.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_dummy',
            field=models.BooleanField(default=False, verbose_name='قيمة افتراضية'),
        ),
        migrations.AddField(
            model_name='department',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='inventory.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.department', verbose_name='الإدارة'),
        ),
        migrations.AddField(
            model_name='sector',
            name='is_dummy',
            field=models.BooleanField(default=False, verbose_name='قيمة افتراضية'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_dummy', models.BooleanField(default=False, verbose_name='قيمة افتراضية')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='inventory.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'دائرة',
                'verbose_name_plural': 'الدوائر',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='inventory.division', verbose_name='الدائرة'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.division', verbose_name='الدائرة'),
        ),
        migrations.RunPython(create_dummy_records, reverse_dummy_records),
    ]
