# Generated by Django 4.2.7 on 2025-11-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_organizational_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='is_dummy',
            field=models.BooleanField(default=False, verbose_name='قيمة افتراضية'),
        ),
    ]
