# Generated by Django 4.2.7 on 2025-11-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_is_dummy_to_administrative_unit'),
    ]

    def migrate_hierarchy_data(apps, schema_editor):
        AdministrativeUnit = apps.get_model('inventory', 'AdministrativeUnit')
        Department = apps.get_model('inventory', 'Department')
        Division = apps.get_model('inventory', 'Division')
        Car = apps.get_model('inventory', 'Car')
        Equipment = apps.get_model('inventory', 'Equipment')
        Sector = apps.get_model('inventory', 'Sector')

        dummy_sector = Sector.objects.filter(name='غير محدد', is_dummy=True).first()
        dummy_admin_unit = None
        if dummy_sector:
            dummy_admin_unit, _ = AdministrativeUnit.objects.get_or_create(
                name='غير محدد',
                defaults={'sector': dummy_sector, 'is_dummy': True}
            )
            update_fields = []
            if dummy_admin_unit.sector_id != dummy_sector.id:
                dummy_admin_unit.sector = dummy_sector
                update_fields.append('sector')
            if not dummy_admin_unit.is_dummy:
                dummy_admin_unit.is_dummy = True
                update_fields.append('is_dummy')
            if update_fields:
                dummy_admin_unit.save(update_fields=update_fields)
        else:
            dummy_admin_unit = AdministrativeUnit.objects.filter(name='غير محدد', is_dummy=True).first()

        dept_to_unit = {}
        for dept in Department.objects.all():
            unit, _ = AdministrativeUnit.objects.get_or_create(
                name=dept.name,
                defaults={'sector': dept.sector, 'is_dummy': dept.is_dummy}
            )
            update_fields = []
            if dept.sector and unit.sector_id != dept.sector_id:
                unit.sector = dept.sector
                update_fields.append('sector')
            if dept.is_dummy and not unit.is_dummy:
                unit.is_dummy = True
                update_fields.append('is_dummy')
            if update_fields:
                unit.save(update_fields=update_fields)
            dept_to_unit[dept.pk] = unit

        for division in Division.objects.all():
            if getattr(division, 'administrative_unit_id', None):
                continue
            dept_id = getattr(division, 'department_id', None)
            target_unit = dept_to_unit.get(dept_id)
            if not target_unit and dummy_admin_unit:
                target_unit = dummy_admin_unit
            if target_unit:
                division.administrative_unit = target_unit
                division.save(update_fields=['administrative_unit'])

        for car in Car.objects.all():
            if car.administrative_unit_id:
                continue
            dept_id = car.department_id
            target_unit = dept_to_unit.get(dept_id)
            if not target_unit and dummy_admin_unit:
                target_unit = dummy_admin_unit
            if target_unit:
                car.administrative_unit = target_unit
                car.save(update_fields=['administrative_unit'])

        for equipment in Equipment.objects.all():
            if getattr(equipment, 'administrative_unit_id', None):
                continue
            dept_id = equipment.department_id
            target_unit = dept_to_unit.get(dept_id)
            if not target_unit and dummy_admin_unit:
                target_unit = dummy_admin_unit
            if target_unit:
                equipment.administrative_unit = target_unit
                equipment.save(update_fields=['administrative_unit'])

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_units', to='inventory.sector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='division',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='inventory.administrativeunit', verbose_name='الإدارة'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='administrative_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_by_unit', to='inventory.administrativeunit', verbose_name='الإدارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_by_department', to='inventory.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.department', verbose_name='القسم'),
        ),
        migrations.RunPython(migrate_hierarchy_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='division',
            name='department',
        ),
    ]
