# Generated by Django 4.2.7 on 2025-11-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_division_department_administrativeunit_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sector',
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='inventory.division', verbose_name='الدائرة'),
        ),
    ]
