# Generated by Django 5.2.7 on 2025-11-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_department_sector_department_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'صورة معدة', 'verbose_name_plural': 'صور المعدات'},
        ),
    ]
